### ISSUE TITLE
Move "getting started"-notebook to its separate tab

### ISSUE THREAD

**Issue by JrtPec** [opengridcc/opengridcc.github.io#2]
I think this notebook (nice work @saroele :-) deserves its own tab on the website

**Comment by saroele** [comment]
exactly. so why don't you check the site, it's already there :-D

**Comment by JrtPec** [comment]
I know 👍 what I meant was to put in on top, next to 'about' and 'get involved'. It deserves to be more prominent than the other analyses.

**Comment by saroele** [comment]
Sorry, i replied via email, didn't see that you created a separate issue.  
Ok, i think it's a good idea to put it somewhere more visible.
