### ISSUE TITLE
Live example link on website

### ISSUE THREAD

**Issue by maxhelskens** [opengridcc/opengridcc.github.io#5]
Link the analyses tot the live binder notebooks

**Comment by JrtPec** [comment]
I get a "403 Forbidden" error when I click the Live Demo links on the website

**Comment by saroele** [comment]
Me too :-(

**Comment by maxhelskens** [comment]
Easy fix: my binder was already loaded when i was testing it so i used the direct url and it worked. When binder isn't loaded this url doesn't work, we need to us the filepath argument to the notebook we want to load. See: https://mybinder.org/#

https://mybinder.org/v2/gh/opengridcc/opengrid-demo/master?filepath=

**Comment by saroele** [comment]
Seems ok now 👍
